"""
Image/shape pixel constants
"""

DIM = 64
X_MIN, X_MAX = (8, 48)
ONE_QUARTER = (X_MAX - X_MIN) // 3
X_MIN_34, X_MAX_34 = (X_MIN + ONE_QUARTER, X_MAX - ONE_QUARTER)
BUFFER = 10
SIZE_MIN, SIZE_MAX = (2, 8)

MAX_PLACEMENT_ATTEMPTS = 20
MAX_DISTRACTOR_PLACEMENT_ATTEMPTS = 100
MAX_INVALIDATE_ATTEMPTS = 100
